### ISSUE TITLE
Some HTML validating errors in BE

### ISSUE THREAD

**Issue by Aybee** [menatwork/MultiColumnWizard#201]
Hallo,

vielleicht könnt ihr das hier korrigieren, sodass man keine Fehler mehr beim Validieren im BE bekommt.

``` html
<table
  cellspacing="0"
  rel="maxCount[1] minCount[0] unique[] datepicker[]"
  cellpadding="0"
  id="ctrl_dma_simplegrid_columnsettings"
  class="tl_modulewizard multicolumnwizard"
  summary="MultiColumnWizard"
>
=>
<table
  rel="maxCount[1] minCount[0] unique[] datepicker[]"
  id="ctrl_dma_simplegrid_columnsettings"
  class="tl_modulewizard multicolumnwizard"
>
```

https://github.com/menatwork/MultiColumnWizard/blob/f7da67e92680c440786d21cfb5568e5c10bba3f2/system/modules/multicolumnwizard/MultiColumnWizard.php#L1096

Das `rel="..."` wäre dann allerdings immer noch invalide. Vielleicht könnte das dann auch noch nach `data-options="..."` o.ä. geändert werden.

**Comment by Aybee** [comment]
No feedback so  far. Now I like to push this one.

**Comment by discordier** [comment]
I guess more details of what is wrong could speed up processing of the issue.
If I understand correctly, you want to remove the `cellspacing`, `cellpadding` and `summary` attributes altogether and change `rel` to `data-options`.

If so, please go ahead and provide a pull request.
Please do not forget to add the relevant stuff to the css though.
```css
/* cellspacing="0" */
.tl_modulewizard.multicolumnwizard { border-collapse: collapse; border-spacing: 0; }
/* cellpadding="0" */
.tl_modulewizard.multicolumnwizard th, td { padding: 0px; }

```
